/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeInterface;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import loginInterface.SignIn;

/**
 *
 * @author 2ndyrGroupB
 */
public class ApplyLeave extends javax.swing.JInternalFrame {
     private int emp_ID=new SignIn().empID;
    /**
     * Creates new form ApplyLeave
     */
    public ApplyLeave() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emp_Fdate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_leave_des = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        emp_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emp_Tdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emp_Ltype = new javax.swing.JTextField();
        btnLeave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 530));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Email :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        emp_Fdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_FdateActionPerformed(evt);
            }
        });
        jPanel1.add(emp_Fdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 220, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Leave Description :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        emp_leave_des.setColumns(20);
        emp_leave_des.setRows(5);
        jScrollPane1.setViewportView(emp_leave_des);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 290, 148));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("From Date :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        emp_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(emp_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 257, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("To Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        emp_Tdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emp_Tdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_TdateActionPerformed(evt);
            }
        });
        jPanel1.add(emp_Tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 220, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Type :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, 20));

        emp_Ltype.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emp_Ltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_LtypeActionPerformed(evt);
            }
        });
        jPanel1.add(emp_Ltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 220, 40));

        btnLeave.setBackground(new java.awt.Color(0, 204, 0));
        btnLeave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLeave.setForeground(new java.awt.Color(240, 240, 240));
        btnLeave.setText("Apply Leave");
        btnLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLeaveMouseClicked(evt);
            }
        });
        jPanel1.add(btnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 400, 110, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Apply Leave Form");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 47));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_FdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_FdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_FdateActionPerformed

    private void emp_LtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_LtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_LtypeActionPerformed

    private void emp_TdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_TdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_TdateActionPerformed

    private void btnLeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeaveMouseClicked
        // TODO add your handling code here:
        String status = "Request";
        try {  
        Class.forName("com.mysql.jdbc.Driver");  
        // establish connection  
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sd-202", "root", "");  
        Statement statement = con.createStatement();  
        statement.execute("INSERT INTO employee_leave (emp_id, email, leave_des, from_date, to_date,type,status)VALUES('"+ emp_ID + "','" + emp_email.getText() + "','" + emp_leave_des.getText() +"','"+emp_Fdate.getText()+"','"+emp_Tdate.getText()+"','"+emp_Ltype.getText()+"','"+ status + "')");  
        JOptionPane.showMessageDialog(null, "Record inserted...");    
        refresh(); //Calling Referesh() method  
    } catch (SQLException | ClassNotFoundException e) {  
        JOptionPane.showMessageDialog(null, e);  
    }  
        
        
    }//GEN-LAST:event_btnLeaveMouseClicked
    public void refresh(){
        emp_email.setText("");
        emp_leave_des.setText("");
        emp_Fdate.setText("");
        emp_Tdate.setText("");
        emp_Ltype.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeave;
    private javax.swing.JTextField emp_Fdate;
    private javax.swing.JTextField emp_Ltype;
    private javax.swing.JTextField emp_Tdate;
    private javax.swing.JTextField emp_email;
    private javax.swing.JTextArea emp_leave_des;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
