/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginInterface;

import AdminInterface.AdminDirectory;
import EmployeeInterface.EmployeeMainDirectory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author 2ndyrGroupB
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public SignIn() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userEmail = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sigiin = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("SIGN IN ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        userEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailActionPerformed(evt);
            }
        });
        jPanel1.add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 272, 40));

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setText("User Email :");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 111, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 220, -1, -1));

        sigiin.setBackground(new java.awt.Color(38, 153, 0));
        sigiin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sigiin.setForeground(new java.awt.Color(240, 240, 240));
        sigiin.setText("Sign In");
        sigiin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sigiinMouseClicked(evt);
            }
        });
        sigiin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigiinActionPerformed(evt);
            }
        });
        jPanel1.add(sigiin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 270, 40));

        pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 251, 270, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailActionPerformed

    private void sigiinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigiinActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_sigiinActionPerformed
    public static int empID;
    private void sigiinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigiinMouseClicked
        // TODO add your handling code here:

        String userName = userEmail.getText();
        String temp_pwd = String.valueOf(pass.getPassword());
        int type = 0;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sd-202", "root", "");
            PreparedStatement st = (PreparedStatement) con.prepareStatement("Select * from employee where email=? and password=?");
            st.setString(1, userName);
            st.setString(2, temp_pwd);
            ResultSet rs = st.executeQuery();
            if (userName.equals("admin") && temp_pwd.equals("admin")) {
                type = 1;
            } else if (rs.next()) {
                empID = rs.getInt("emp_id");
                new EmployeeMainDirectory().setVisible(true);
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "You have successfully logged in");
            } else {
                JOptionPane.showMessageDialog(null, "Wrong Username & Password");
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        if (type == 1) {
            new AdminDirectory().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_sigiinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton sigiin;
    private javax.swing.JTextField userEmail;
    // End of variables declaration//GEN-END:variables
}
