/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems.admin.ui;

import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author 2ndyrGroupB
 */
public class AddLeave extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddLeave
     */
    public AddLeave() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_leavedesTextField = new javax.swing.JTextArea();
        emp_idTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emp_emailTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        leave_status = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        leave_tDateTextField = new com.toedter.calendar.JDateChooser();
        leave_fDateTextField1 = new com.toedter.calendar.JDateChooser();
        leave_typeTextField = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1010, 625));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Leave");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Email :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Leave Description :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("From Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Leave Type: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Status :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        emp_leavedesTextField.setColumns(20);
        emp_leavedesTextField.setRows(5);
        jScrollPane1.setViewportView(emp_leavedesTextField);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 340, 140));

        emp_idTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(emp_idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 280, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Employee ID#");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        emp_emailTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(emp_emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 280, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Add Leave");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, -1, 40));

        leave_status.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        leave_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Request", "Approved", "Reject" }));
        jPanel1.add(leave_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 300, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("To Date :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        leave_tDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(leave_tDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 300, 40));

        leave_fDateTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(leave_fDateTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 300, 40));

        leave_typeTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        leave_typeTextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Vacation Leave", "Parental Leave", "Leave for personal or family reasons and special leave", "Leave of absence for community service", "Long leave of absence", "Study Leave", "Sick Leave" }));
        leave_typeTextField.setToolTipText("");
        jPanel1.add(leave_typeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 341, 300, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String leave_stat = String.valueOf(leave_status.getSelectedItem());
        String leave_type = String.valueOf(leave_typeTextField.getSelectedItem());
        if (emp_idTextField.getText().isEmpty() || emp_emailTextField.getText().isEmpty() || emp_leavedesTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required.. Please fill out all required fields...");
        } else if (leave_fDateTextField1.getDate() == null || leave_tDateTextField.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Invalid Date");
        } else if(leave_type.equals("Choose")){
            JOptionPane.showMessageDialog(null, "Invalid leave type selection...");
        }else if(leave_stat.equals("Choose")){
            JOptionPane.showMessageDialog(null, "Invalid leave status selection...");
        }
        else {
            Object[] options = {"Yes", "No"};
            int n = JOptionPane.showOptionDialog(null,
                    "Would you like to add this data?",
                    "Add Leave",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]);
            if (n == JOptionPane.YES_OPTION) {
                try {
                    int emp_id = Integer.parseInt(emp_idTextField.getText());
                    try {
                        SimpleDateFormat dFormat = new SimpleDateFormat("MMM dd,yyyy");
                        String fromDate = fromDate = dFormat.format(leave_fDateTextField1.getDate());
                        String toDate = toDate = dFormat.format(leave_tDateTextField.getDate());
                        Class.forName("com.mysql.jdbc.Driver");
                        // establish connection  
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sd-202", "root", "");
                        Statement statement = con.createStatement();
                        statement.execute("INSERT INTO employee_leave (emp_id, email, leave_des, from_date, to_date,type,status)VALUES('" + emp_id + "','" + emp_emailTextField.getText() + "','" + emp_leavedesTextField.getText() + "','" + fromDate + "','" + toDate + "','" + leave_type + "','" + leave_stat + "')");
                        JOptionPane.showMessageDialog(null, "Record inserted...");
                        //refresh(); //Calling Referesh() method  
                    } catch (SQLException | ClassNotFoundException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, emp_idTextField.getText() + " is not a valid integer");
                }

            } else {
                this.setEnabled(true);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emp_emailTextField;
    private javax.swing.JTextField emp_idTextField;
    private javax.swing.JTextArea emp_leavedesTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser leave_fDateTextField1;
    private javax.swing.JComboBox<String> leave_status;
    private com.toedter.calendar.JDateChooser leave_tDateTextField;
    private javax.swing.JComboBox<String> leave_typeTextField;
    // End of variables declaration//GEN-END:variables
}
