/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems.admin.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author 2ndyrGroupB
 */
public class AddTask extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddTask
     */
    public AddTask() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        task_workTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        task_des = new javax.swing.JTextArea();
        task_empId = new javax.swing.JTextField();
        task_email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        task_dDate = new com.toedter.calendar.JDateChooser();
        task_sDate = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(1010, 625));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Task");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Employee ID# :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Work Title :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Task Description :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Email :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Due Date :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        task_workTitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        task_workTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_workTitleActionPerformed(evt);
            }
        });
        getContentPane().add(task_workTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 280, 40));

        task_des.setColumns(20);
        task_des.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        task_des.setRows(5);
        jScrollPane1.setViewportView(task_des);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 350, 140));

        task_empId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        task_empId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_empIdActionPerformed(evt);
            }
        });
        getContentPane().add(task_empId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 280, 40));

        task_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        task_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_emailActionPerformed(evt);
            }
        });
        getContentPane().add(task_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 270, 40));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Add Task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 140, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Starting Date :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        task_dDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(task_dDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 270, 40));

        task_sDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(task_sDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 270, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void task_workTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_workTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_workTitleActionPerformed

    private void task_empIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_empIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_empIdActionPerformed

    private void task_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_emailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (task_empId.getText().isEmpty() || task_email.getText().isEmpty() || task_workTitle.getText().isEmpty() || task_des.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All field are required.. Please fill out all field...");
        } else if (task_sDate.getDate() == null || task_dDate.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Invalid Date Selection...");
        } else {
            Object[] options = {"Yes", "No"};
            int n = JOptionPane.showOptionDialog(null,
                    "Would you like to add this data?",
                    "Add Employee Task",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]);
            if (n == JOptionPane.YES_OPTION) {
                try {
                    int emp_id = Integer.parseInt(task_empId.getText());
                    try {
                        SimpleDateFormat dFormat = new SimpleDateFormat("MMM dd,yyyy");
                        String startDate = dFormat.format(task_sDate.getDate());
                        String dueDate = dFormat.format(task_dDate.getDate());
                        Class.forName("com.mysql.jdbc.Driver");
                        // establish connection  
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sd-202", "root", "");
                        Statement statement = con.createStatement();
                        statement.execute("INSERT INTO employee_task (emp_id, email, work_title, task_des, s_date,d_date)VALUES('" + emp_id + "','" + task_email.getText() + "','" + task_workTitle.getText() + "','" + task_des.getText() + "','" + startDate + "','" + dueDate + "')");
                        JOptionPane.showMessageDialog(null, "Task added succesfully...");
                        //refresh(); //Calling Referesh() method  
                    } catch (SQLException | ClassNotFoundException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                } catch (NumberFormatException e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, task_empId.getText() + "Employee ID is not a valid integer");
                }

            } else {
                this.setEnabled(true);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser task_dDate;
    private javax.swing.JTextArea task_des;
    private javax.swing.JTextField task_email;
    private javax.swing.JTextField task_empId;
    private com.toedter.calendar.JDateChooser task_sDate;
    private javax.swing.JTextField task_workTitle;
    // End of variables declaration//GEN-END:variables
}
