/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems.admin.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2ndyrGroupB
 */
public class ManageLeave extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManageLeave
     */
    public ManageLeave() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        leave_id.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        f_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_leaveDes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        emp_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        leave_id = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewAllLeaveData = new javax.swing.JTable();
        searchTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        leave_type = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewSelectDataTable = new javax.swing.JTable();
        t_date = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emp_IdData = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        leave_status = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1010, 625));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Leave ID# :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        f_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_dateActionPerformed(evt);
            }
        });
        jPanel1.add(f_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Leave Description :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        emp_leaveDes.setColumns(20);
        emp_leaveDes.setRows(5);
        jScrollPane1.setViewportView(emp_leaveDes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("From Date :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, 20));

        emp_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(emp_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Leave Type :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Status :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 204, 0));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(240, 240, 240));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Manage Leave");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 0, 190, 47));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Email :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        leave_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(leave_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 32));

        deleteBtn.setBackground(new java.awt.Color(204, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(240, 240, 240));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, 32));

        viewAllLeaveData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAllLeaveData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        viewAllLeaveData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Leave ID#", "Employee ID", "Email", "Description", "From Date", "To Date", "Leave Type", "Status"
            }
        ));
        jScrollPane2.setViewportView(viewAllLeaveData);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 705, 260));

        searchTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtFieldKeyTyped(evt);
            }
        });
        jPanel1.add(searchTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 180, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Operations :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        leave_type.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        leave_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Vacation Leave", "Parental Leave", "Leave for personal or family reasons and special leave", "Leave of absence for community service", "Long leave of absence", "Study Leave", "Sick Leave" }));
        jPanel1.add(leave_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 190, 30));

        viewSelectDataTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewSelectDataTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        viewSelectDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Leave ID#", "Employee ID", "Email", "Description", "From Date", "To Date", "Leave Type ", "Status"
            }
        ));
        viewSelectDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSelectDataTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(viewSelectDataTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 53, 705, 210));

        t_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(t_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 190, 31));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("To Date :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        emp_IdData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(emp_IdData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 32));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Employee ID# :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("SEARCH");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 30));

        leave_status.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        leave_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Request", "Approved", "Reject" }));
        jPanel1.add(leave_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_dateActionPerformed

    private void viewSelectDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSelectDataTableMouseClicked
        // TODO add your handling code here:        
        DefaultTableModel data = (DefaultTableModel) viewSelectDataTable.getModel();
        int selectIndex = viewSelectDataTable.getSelectedRow();
        leave_id.setText(data.getValueAt(selectIndex, 0).toString());
        emp_IdData.setText(data.getValueAt(selectIndex, 1).toString());
        emp_email.setText(data.getValueAt(selectIndex, 2).toString());
        emp_leaveDes.setText(data.getValueAt(selectIndex, 3).toString());
        f_date.setText(data.getValueAt(selectIndex, 4).toString());
        t_date.setText(data.getValueAt(selectIndex, 5).toString());
      

    }//GEN-LAST:event_viewSelectDataTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        String emp_id = leave_id.getText();
        String emp_emailTf = emp_email.getText();
        String leave_des = emp_leaveDes.getText();
        String laeveF_date = f_date.getText();
        String leaveT_date = t_date.getText();
        String leave_t = String.valueOf(leave_type.getSelectedItem());
        String leave_stat = String.valueOf(leave_status.getSelectedItem());
        
//        if(emp_id.isEmpty()|| emp_emailTf.isEmpty() || leave_des.isEmpty() || leave_des.isEmpty())       
        Object[] options = {"Yes", "No"};
        int n = JOptionPane.showOptionDialog(null,
                "Would you like to update this data?",
                "Update",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if (n == JOptionPane.YES_OPTION) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                // establish connection  
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sd-202", "root", "");
                Statement statement = con.createStatement();
                statement.executeUpdate("Update employee_leave set email = '" + emp_emailTf + "',leave_des ='" + leave_des + "', from_date='" + laeveF_date + "', to_date='" + leaveT_date + "', type='" + leave_t + "', status='" + leave_stat + "' WHERE leave_id='" + emp_id + "' ");
                JOptionPane.showMessageDialog(null, "Record has been updated...");
                statement.close();
                con.close();
                //Referesh(); //Calling Referesh() method  
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Data was not update successfully ");;
            }
        } else {
            this.setEnabled(true);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Yes", "No"};
        int n = JOptionPane.showOptionDialog(null,
                "Would you like to delete this data?",
                "WARNING!",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if (n == JOptionPane.YES_OPTION) {
             try {
                Class.forName("com.mysql.jdbc.Driver");
                // establish connection  
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sd-202", "root", "");
                Statement statement = con.createStatement();
                statement.executeUpdate("DELETE FROM employee_leave WHERE leave_id ='" + leave_id.getText() + "'");
                JOptionPane.showMessageDialog(null, "Record deleted...");
                statement.close();
                con.close();
                //Referesh(); //Calling Referesh() method  
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Data was not delete successfully ");
            }
        } else {
            this.setEnabled(true);
        } 

           
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtFieldKeyTyped
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) viewSelectDataTable.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
        search();
    }//GEN-LAST:event_searchTxtFieldKeyTyped

    private void searchTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtFieldKeyReleased
        // TODO add your handling code here:
         if (searchTxtField.getText().isEmpty()) {
            DefaultTableModel dm = (DefaultTableModel) viewSelectDataTable.getModel();
            dm.getDataVector().removeAllElements();
            dm.fireTableDataChanged();
        }
    }//GEN-LAST:event_searchTxtFieldKeyReleased

    

    public void viewAllLeave() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sd-202", "root", "");
            PreparedStatement pstm = con.prepareStatement("SELECT * FROM employee_leave");
            ResultSet rs = pstm.executeQuery();
            DefaultTableModel model = (DefaultTableModel) viewAllLeaveData.getModel();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getInt(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    private void search(){
          String searchTxt = searchTxtField.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sd-202", "root", "");
            PreparedStatement pstm = con.prepareStatement("SELECT * FROM employee_leave where leave_id LIKE '%" + searchTxt + "%' OR emp_id LIKE '%" + searchTxt + "%' OR email LIKE '%" + searchTxt + "%' OR from_date LIKE '%" + searchTxt + "%' OR to_date LIKE '%" + searchTxt + "%' OR type LIKE '%" + searchTxt + "%' OR status LIKE '%" + searchTxt + "%'");
            ResultSet rs = pstm.executeQuery();
            DefaultTableModel model = (DefaultTableModel) viewSelectDataTable.getModel();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getInt(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emp_IdData;
    private javax.swing.JTextField emp_email;
    private javax.swing.JTextArea emp_leaveDes;
    private javax.swing.JTextField f_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField leave_id;
    private javax.swing.JComboBox<String> leave_status;
    private javax.swing.JComboBox<String> leave_type;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JTextField t_date;
    private javax.swing.JTable viewAllLeaveData;
    private javax.swing.JTable viewSelectDataTable;
    // End of variables declaration//GEN-END:variables
}
