/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems.admin.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2ndyrGroupB
 */
public class TaskManager extends javax.swing.JInternalFrame {

    /**
     * Creates new form TaskManager
     */
    public TaskManager() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        task_id.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        task_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        task_des = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        task_workTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        task_sDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        task_dDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        task_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allTaskTable = new javax.swing.JTable();
        searchTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        task_empId = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        viewSelectedData = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1010, 625));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Task Manager ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Task ID# :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        task_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        task_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_emailActionPerformed(evt);
            }
        });
        getContentPane().add(task_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 199, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Task Description :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        task_des.setColumns(20);
        task_des.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        task_des.setRows(5);
        jScrollPane1.setViewportView(task_des);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Email :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 40, -1));

        task_workTitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(task_workTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 199, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Starting Date :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        task_sDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(task_sDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Due Date :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        task_dDate.setText(" ");
        getContentPane().add(task_dDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Operations :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 80, -1));

        updateBtn.setBackground(new java.awt.Color(0, 0, 255));
        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(240, 240, 240));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, 30));

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(240, 240, 240));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, -1, 30));

        task_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        task_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_idActionPerformed(evt);
            }
        });
        getContentPane().add(task_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 199, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Work Title :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        allTaskTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        allTaskTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        allTaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID#", "Emp ID#", "Email", "Work Title", "Task Description", "Starting Date", "Due Date"
            }
        ));
        jScrollPane3.setViewportView(allTaskTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 720, 290));

        searchTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTxtFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtFieldKeyTyped(evt);
            }
        });
        getContentPane().add(searchTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Employee ID# :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        task_empId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        task_empId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_empIdActionPerformed(evt);
            }
        });
        getContentPane().add(task_empId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 199, 30));

        viewSelectedData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewSelectedData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        viewSelectedData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID#", "Emp ID#", "Email", "Work Title", "Task Description", "Starting Date", "Due Date"
            }
        ));
        viewSelectedData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSelectedDataMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(viewSelectedData);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 720, 160));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("SEARCH");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void task_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_emailActionPerformed

    private void task_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_idActionPerformed

    private void task_empIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_empIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_empIdActionPerformed

    private void viewSelectedDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSelectedDataMouseClicked
        // TODO add your handling code here: 
        DefaultTableModel data = (DefaultTableModel) viewSelectedData.getModel();
        int selectIndex = viewSelectedData.getSelectedRow();
        task_id.setText(data.getValueAt(selectIndex, 0).toString());
        task_empId.setText(data.getValueAt(selectIndex, 1).toString());
        task_email.setText(data.getValueAt(selectIndex, 2).toString());
        task_workTitle.setText(data.getValueAt(selectIndex, 3).toString());
        task_des.setText(data.getValueAt(selectIndex, 4).toString());
        task_sDate.setText(data.getValueAt(selectIndex, 5).toString());
        task_dDate.setText(data.getValueAt(selectIndex, 6).toString());
    }//GEN-LAST:event_viewSelectedDataMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:

        Object[] options = {"Yes", "No"};
        int n = JOptionPane.showOptionDialog(null,
                "Would you like to delete this data?",
                "WARNING!",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if (n == JOptionPane.YES_OPTION) {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                // establish connection  
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sd-202", "root", "");
                Statement statement = con.createStatement();
                statement.executeUpdate("DELETE FROM employee_task WHERE task_id ='" + task_id.getText() + "'");
                JOptionPane.showMessageDialog(null, "Record has been deleted successfully...");
                statement.close();
                con.close();
                //Referesh(); //Calling Referesh() method  
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Data was not deleted successfully ");
            }

        } else {
            this.setEnabled(true);
        }


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        Object[] options = {"Yes", "No"};
        int n = JOptionPane.showOptionDialog(null,
                "Would you like to update this data?",
                "WARNING!",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if (n == JOptionPane.YES_OPTION) {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                // establish connection  
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sd-202", "root", "");
                Statement statement = con.createStatement();
                statement.executeUpdate("Update employee_task set emp_id='" + task_empId.getText() + "', email = '" + task_email.getText() + "',work_title='" + task_workTitle.getText() + "', task_des='" + task_des.getText() + "', s_date='" + task_sDate.getText() + "', d_date='" + task_dDate.getText() + "' WHERE task_id='" + task_id.getText() + "' ");
                JOptionPane.showMessageDialog(null, "Record has been updated...");
                statement.close();
                con.close();
                //Referesh(); //Calling Referesh() method  
            } catch (SQLException | ClassNotFoundException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Data was not update successfully ");;
            }
        } else {
            this.setEnabled(true);
        }


    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchTxtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtFieldKeyTyped
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) viewSelectedData.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
        search();
    }//GEN-LAST:event_searchTxtFieldKeyTyped

    private void searchTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtFieldKeyPressed

    private void searchTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtFieldKeyReleased
        // TODO add your handling code here:
         if (searchTxtField.getText().isEmpty()) {
            DefaultTableModel dm = (DefaultTableModel) viewSelectedData.getModel();
            dm.getDataVector().removeAllElements();
            dm.fireTableDataChanged();
        }
    }//GEN-LAST:event_searchTxtFieldKeyReleased
    public void viewAllTask() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sd-202", "root", "");
            PreparedStatement pstm = con.prepareStatement("SELECT * FROM employee_task");
            ResultSet rs = pstm.executeQuery();
            DefaultTableModel model = (DefaultTableModel) allTaskTable.getModel();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getInt(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void search() {
        String searchTxt = searchTxtField.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sd-202", "root", "");
            PreparedStatement pstm = con.prepareStatement("SELECT * FROM employee_task where task_id LIKE '%" + searchTxt + "%' OR emp_id LIKE '%" + searchTxt + "%' OR email LIKE '%" + searchTxt + "%' OR work_title LIKE '%" + searchTxt + "%'");
            ResultSet rs = pstm.executeQuery();
            DefaultTableModel model = (DefaultTableModel) viewSelectedData.getModel();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getInt(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, searchTxtField.getText() + " is not found...");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allTaskTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JTextField task_dDate;
    private javax.swing.JTextArea task_des;
    private javax.swing.JTextField task_email;
    private javax.swing.JTextField task_empId;
    private javax.swing.JTextField task_id;
    private javax.swing.JTextField task_sDate;
    private javax.swing.JTextField task_workTitle;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTable viewSelectedData;
    // End of variables declaration//GEN-END:variables
}
