/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems.employee.ui;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import com.ems.login.ui.Login;


/**
 *
 * @author 2ndyrGroupB
 */
public class AddTimeRecord extends javax.swing.JInternalFrame {

    private int emp_ID = new Login().empID;
    private static String emp_timeIn;
    private static String emp_date;
    private static String emp_timeOut;

    /**
     * Creates new form AddTimeRecord
     */
    public AddTimeRecord() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTimeIn = new javax.swing.JButton();
        btnTimeOut = new javax.swing.JButton();
        btnTimeRecord = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setPreferredSize(new java.awt.Dimension(790, 530));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Time Record");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        btnTimeIn.setBackground(new java.awt.Color(0, 51, 204));
        btnTimeIn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTimeIn.setForeground(new java.awt.Color(240, 240, 240));
        btnTimeIn.setText("Time in");
        btnTimeIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimeInMouseClicked(evt);
            }
        });
        btnTimeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeInActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 50));

        btnTimeOut.setBackground(new java.awt.Color(51, 153, 0));
        btnTimeOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTimeOut.setForeground(new java.awt.Color(240, 240, 240));
        btnTimeOut.setText("Time out");
        btnTimeOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimeOutMouseClicked(evt);
            }
        });
        jPanel1.add(btnTimeOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 140, 50));

        btnTimeRecord.setBackground(new java.awt.Color(0, 153, 153));
        btnTimeRecord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTimeRecord.setForeground(new java.awt.Color(240, 240, 240));
        btnTimeRecord.setText("Add Record");
        btnTimeRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimeRecordMouseClicked(evt);
            }
        });
        btnTimeRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeRecordActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimeRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 230, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String subStringTime(String time) {
        String[] sub_time = time.split(":");
        int hour = Integer.parseInt(sub_time[0].trim());
        String newTime;
        if (hour > 11) {
            newTime = time + " PM";
        } else {
            newTime = time + " AM";
        }
        return newTime;
    }

    private String calculateHours(String sTimeIn, String sTimeOut) {
        final String timePattern = "[0-2][0-9]:[0-5][0-9]";

        if (sTimeIn == null || sTimeOut == null || !sTimeIn.matches(timePattern) || !sTimeIn.matches(timePattern)) {
            throw new IllegalArgumentException();
        }

        String[] timeIn = sTimeIn.split(":");
        String[] timeOut = sTimeOut.split(":");

        int inMinutes = 60 * Integer.valueOf(timeIn[0]) + Integer.valueOf(timeIn[1]);
        int outMinutes = 60 * Integer.valueOf(timeOut[0]) + Integer.valueOf(timeOut[1]);

        int diff = 0;
        if (outMinutes > inMinutes) {
            diff = outMinutes - inMinutes;
        } else if (outMinutes < inMinutes) {
            diff = outMinutes + 24 * 60 - inMinutes;
        }
        String totalHours = String.valueOf(diff / 60) + ":" + String.valueOf(diff % 60);
        return totalHours;
    }
    private  int totalhours(int num){
         String totalHours = calculateHours(emp_timeIn, emp_timeOut);
         String[] time_total = totalHours.split(":");
         int finalTotalHours = Integer.valueOf(time_total[num]);
         return finalTotalHours;
    }
    
    private int totalOverTimeHours(int num){
        String totalHours = calculateHours(emp_timeIn, emp_timeOut);
            String[] time_total = totalHours.split(":");
            int overTimeHours = Integer.valueOf(time_total[0]) - num;
            int finalOverTimeHours;
            if (overTimeHours > 0) {
                finalOverTimeHours = overTimeHours;
            } else {
                finalOverTimeHours = 0;
            }
        return finalOverTimeHours;
    }
    private void btnTimeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimeInActionPerformed

    private void btnTimeInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimeInMouseClicked
        // TODO add your handling code here:
        try {
           final DateFormat timeFormat = new SimpleDateFormat("HH:mm");
            Date date = new Date();
            String time = timeFormat.format(date);
            emp_timeIn = time;
            System.out.println(time);
        } catch (DateTimeException e) {
            System.out.println(e);
        }
//          System.out.println(time);    
        JOptionPane.showMessageDialog(null, "Successfull time in...");

    }//GEN-LAST:event_btnTimeInMouseClicked

    private void btnTimeOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimeOutMouseClicked
      try {
            final DateFormat timeFormat = new SimpleDateFormat("HH:mm");
            Date date = new Date();
            String time = timeFormat.format(date);
            emp_timeOut = time;
        } catch (DateTimeException e) {
            System.out.println(e);
        }
        JOptionPane.showMessageDialog(null, "Successfull time out...");
    }//GEN-LAST:event_btnTimeOutMouseClicked


    private void btnTimeRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimeRecordMouseClicked
        // TODO add your handling code here: 

    }//GEN-LAST:event_btnTimeRecordMouseClicked

    private void btnTimeRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeRecordActionPerformed
        // TODO add your handling code here:         
        if (emp_timeIn == null) {
            JOptionPane.showMessageDialog(null, "Please press time in button...");
        } else if (emp_timeOut==null) {
            JOptionPane.showMessageDialog(null, "Please prees time out button...");
        } else {
            String pattern = "MMM dd,yyyy";
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
            String newDate = simpleDateFormat.format(new Date());
            emp_date = newDate;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                // establish connection  
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sd-202", "root", "");
                Statement statement = con.createStatement();
                statement.execute("INSERT INTO employee_time_record (emp_id, date, time_in, time_out, regular_hours,overtime_hours,total_hours)VALUES('" + emp_ID + "','" + emp_date + "','" + subStringTime(emp_timeIn) + "','" + subStringTime(emp_timeOut) + "','" + 8 + "','" + totalOverTimeHours(8)+ "','" + totalhours(0) + "')");
                JOptionPane.showMessageDialog(null, "Record inserted successfully...");
                emp_timeIn =null;
                emp_timeOut =null;

            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }


    }//GEN-LAST:event_btnTimeRecordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimeIn;
    private javax.swing.JButton btnTimeOut;
    private javax.swing.JButton btnTimeRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

}
