/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems.employee.ui;

import com.ems.database.DBConnection;
import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import com.ems.login.ui.Login;

/**
 *
 * @author 2ndyrGroupB
 */
public class ApplyLeave extends javax.swing.JInternalFrame {

    private int emp_ID = new Login().empID;

    /**
     * Creates new form ApplyLeave
     */
    public ApplyLeave() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        fromDateSetEnable();
        toDateSetEnable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utilCalendarModel1 = new org.jdatepicker.impl.UtilCalendarModel();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateComponentFactory2 = new org.jdatepicker.JDateComponentFactory();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_leave_des = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        emp_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLeave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        emp_Fdate = new com.toedter.calendar.JDateChooser();
        emp_Tdate = new com.toedter.calendar.JDateChooser();
        empLeaveType = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(790, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Email :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Leave Description :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        emp_leave_des.setColumns(20);
        emp_leave_des.setRows(5);
        jScrollPane1.setViewportView(emp_leave_des);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 290, 148));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("From Date :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        emp_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(emp_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 257, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("To Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Type :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, 20));

        btnLeave.setBackground(new java.awt.Color(0, 204, 0));
        btnLeave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLeave.setForeground(new java.awt.Color(240, 240, 240));
        btnLeave.setText("Apply Leave");
        btnLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLeaveMouseClicked(evt);
            }
        });
        jPanel1.add(btnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 400, 110, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Apply Leave Form");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 47));

        emp_Fdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emp_Fdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(emp_Fdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 220, 40));

        emp_Tdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(emp_Tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 220, 40));

        empLeaveType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        empLeaveType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Vacation Leave", "Parental Leave", "Leave for personal or family reasons and special leave", "Leave of absence for community service", "Long leave of absence", "Study Leave", "Sick Leave" }));
        jPanel1.add(empLeaveType, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeaveMouseClicked
        // TODO add your handling code here:

        String status = "Request";
        String leave_type = String.valueOf(empLeaveType.getSelectedItem());
        
        if (emp_email.getText().isEmpty() || emp_leave_des.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "All fields are required.. Please fill out all required fields...");
        } else if (emp_Fdate.getDate() == null || emp_Tdate.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Invalid Date Selection...");
        }else if(leave_type.equals("Choose")){
             JOptionPane.showMessageDialog(null, "Invalid Type Selection...");
        }
        
        else {
            try {
                SimpleDateFormat dFormat = new SimpleDateFormat("MM-dd-yyyy");
                String fromDate = dFormat.format(emp_Fdate.getDate());
                String toDate = dFormat.format(emp_Tdate.getDate());
                Class.forName("com.mysql.jdbc.Driver");
                // establish connection  
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sd-202", "root", "");
                Statement statement = con.createStatement();
                statement.execute("INSERT INTO employee_leave (emp_id, email, leave_des, from_date, to_date,type,status)VALUES('" + emp_ID + "','" + emp_email.getText() + "','" + emp_leave_des.getText() + "','" + fromDate + "','" + toDate + "','" +leave_type + "','" + status + "')");
                JOptionPane.showMessageDialog(null, "Record inserted...");
                refresh(); //Calling Referesh() method  
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }


    }//GEN-LAST:event_btnLeaveMouseClicked
    private void refresh() {
        emp_email.setText("");
        emp_leave_des.setText("");
    }

    private void fromDateSetEnable() {
        JTextFieldDateEditor editorFdate = (JTextFieldDateEditor) emp_Fdate.getDateEditor();
        editorFdate.setEditable(false);
    }

    private void toDateSetEnable() {
        JTextFieldDateEditor editorFdate = (JTextFieldDateEditor) emp_Tdate.getDateEditor();
        editorFdate.setEditable(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeave;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private javax.swing.JComboBox<String> empLeaveType;
    private com.toedter.calendar.JDateChooser emp_Fdate;
    private com.toedter.calendar.JDateChooser emp_Tdate;
    private javax.swing.JTextField emp_email;
    private javax.swing.JTextArea emp_leave_des;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdatepicker.impl.UtilCalendarModel utilCalendarModel1;
    // End of variables declaration//GEN-END:variables
}
